flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:ekmett/quine.git
    commit: da2e3a4531bed0fe39a680b123c460dad0750da2
- location: /home/j/dev/apps/haskell/chart/bindings-GLFW
  extra-dep: true
extra-deps:
- gloss-raster-1.10.2.3
resolver: lts-7.0
